// import Img from "../../../assets/choynak_img.jpg"
import Img from "../../../assets/choynak_img.jpg"
export const product = [
    { id: 1, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
    { id: 2, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
    { id: 3, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
    { id: 4, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
    { id: 5, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
    { id: 6, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
    { id: 7, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
    { id: 8, name: "Elekt choynak 1litr", img: `${Img}`, Sotuvchi: "Chakana savdo", Omborda: "120 dona", price: "99,000so'm", discount: "129,000so'm", desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias, ad minima soluta sequi dolorem delectus" },
]